AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Runtime: provided
    CodeUri: tests/R/
    Layers:
    - !Ref RuntimeLayer
Resources:
  ExampleFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: script.handler
      Timeout: 500
      Environment:
        Variables:
          R_LIBRARY_PATH: s3://wl-dg-ncf-tool/rlibs/library.tar.gz
  RuntimeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: runtime
      ContentUri: runtime/build/layer/
