#!/bin/sh

set -euo pipefail

# Ensure aws is on path
PATH=$PATH:/opt
PATH=$PATH:/opt/awscli
export R_LIBS=/tmp

# Clear out any tmp files so we have enough space
rm -rf /tmp/*

# Extract libraries from s3 into /tmp
if [[ -v R_LIBRARY_PATH ]]
then
    echo "Loading libraries from $R_LIBRARY_PATH"
    aws s3 cp $R_LIBRARY_PATH - | tar xz -C /tmp/
else
    echo "No library path configured"
fi

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)
  
  /opt/R/bin/Rscript /opt/runtime.R "$EVENT_DATA" $REQUEST_ID
done
